name: wpnext-test
recipe: pantheon
config:
  framework: wordpress
  site: wpnext-test
  id: cd0b8608-90bb-4c73-b410-9eec0495a59a
env_file:
  - .env.lando
services:
  appserver:
    overrides:
      volumes:
        # Copy the individual PEM instead of full bundle
        - /Users/chris.reynolds/Certs/cloudflare-gateway.pem:/usr/local/share/ca-certificates/cloudflare.crt:ro
    build_as_root:
      - update-ca-certificates
      - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - chmod +x wp-cli.phar
      - mv wp-cli.phar /usr/local/bin/wp
      - wp --info
