name: Deploy to WPNext-Test

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "Pantheon Robot"
          git config --global user.email "bot@getpantheon.com"
          git remote add pantheon ${{ secrets.GIT_REPO }}

      - name: Install dependencies
        run: composer install

      - name: Commit build artifacts
        run: |
          git add -A
          git commit -m "${{ steps.get_commit.outputs.message }}" || echo "Nothing to commit"

      - name: Push to Pantheon
        run: git push pantheon master --force
