name: Deploy to WPNext-Test

on:
 push:
  branches:
    - main

permissions:
  contents: write
  deployments: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: composer install
      - name: Commit build artifacts
        run: |
          git config --global user.name "Pantheon Robot"
          git config --global user.email "bot@getpantheon.com"
          git add .
          git commit -m "Build: commit composer dependencies" || echo "Nothing to commit"      
      - name: Deploy to Pantheon
        uses: stevector-streaming/dtp@0.2.1
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          site: wpnext-test
          machine_token: ${{ secrets.TERMINUS_TOKEN }}
          git_commit_message: ${{ steps.get_commit.outputs.message }}
 