name: Deploy to WPNext-Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'scripts/*'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      git_user_name: "Pantheon Robot"
      git_user_email: "bot@getpantheon.com"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ env.git_user_name }}"
          git config --global user.email "${{ env.git_user_email }}"
          git remote add pantheon ${{ secrets.GIT_REPO }}

      - name: Configure Pantheon Host Key
        run: |
          echo "Host *.drush.in HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
          echo "Host *.drush.in PubkeyAcceptedKeyTypes +ssh-rsa" >> ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: composer install

      - name: Commit build artifacts
        run: |
          git fetch pantheon
          git checkout -b master
          git add -A
          if git diff --quiet pantheon/master; then
            echo "No changes to commit."
            echo "skip_push=true" >> $GITHUB_ENV
          else
            git commit -m "${{ steps.get_commit.outputs.message }}" || echo "Nothing to commit"
          fi

      - name: Compare commit messages
        id: compare_commits
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%s)
          PREV_COMMIT_MSG=$(git log -2 --pretty=%s | tail -n 1)
          echo "Last commit message: $LAST_COMMIT_MSG"
          echo "Previous commit message: $PREV_COMMIT_MSG"
          if [ "$LAST_COMMIT_MSG" == "$PREV_COMMIT_MSG" ]; then
            echo "Duplicate commit messages detected. Skipping deployment."
            echo "skip_deploy=true" >> $GITHUB_ENV
          fi

      - name: Push to Pantheon
        if: ${{ env.skip_deploy != 'true' }}
        uses: stevector/push-to-pantheon@0.5.0
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          machine_token: ${{ secrets.TERMINUS_TOKEN }}
          site: wpnext-test
          git_user_name: ${{ env.git_user_name }}
          git_user_email: ${{ env.git_user_email }}
          git_commit_message: ${{ steps.get_commit.outputs.message }}
