name: Deploy to WPNext-Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: write
  deployments: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@v1
        with:
          pantheon-machine-token: ${{ secrets.TERMINUS_TOKEN }}

      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: dev
          ref: ${{ github.head_ref }}

      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Pantheon Host Key
        run: |
          echo "Host *.drush.in HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
          echo "Host *.drush.in PubkeyAcceptedKeyTypes +ssh-rsa" >> ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Configure Git
        run: |
          git config --global user.name "Pantheon Robot"
          git config --global user.email "bot@getpantheon.com"
          git remote add pantheon ${{ secrets.GIT_REPO }}

      - name: Install dependencies
        run: composer install

      - name: Commit build artifacts
        run: |
          git checkout -b master
          git add -A
          if git diff --quiet pantheon/master; then
            echo "No changes to commit."
            echo "skip_push=true" >> $GITHUB_ENV
          else
            git commit -m "${{ steps.get_commit.outputs.message }}" || echo "Nothing to commit"
          fi

      - name: Compare commit messages
        id: compare_commits
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%s)
          PREV_COMMIT_MSG=$(git log -2 --pretty=%s | tail -n 1)
          echo "Last commit message: $LAST_COMMIT_MSG"
          echo "Previous commit message: $PREV_COMMIT_MSG"
          if [ "$LAST_COMMIT_MSG" == "$PREV_COMMIT_MSG" ]; then
            echo "Duplicate commit messages detected. Skipping deployment."
            echo "skip_deploy=true" >> $GITHUB_ENV
          fi

      - name: Push to Pantheon
        if: env.skip_push != 'true'
        run: |
          git push --set-upstream pantheon master --force
          terminus workflow:wait wpnext-test.dev

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          ref: ${{ github.head_ref }}
          # todo, how does this work when there is a step above with the id of "deployment" not "deployment_id"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: dev
          env_url: https://dev-wpnext-test.pantheonsite.io
