name: Shellcheck

on:
  push:
    paths:
      - 'scripts/*.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'
        env:
          SHELLCHECK_OPTS: -e SC1094